### ISSUE TITLE
[bug] No mystical gemstone and trader icon on map on dedicated server

### ISSUE THREAD

**Issue by Juraszka** [blaxxun-boop/Jewelcrafting#19]
The newest version of mod, oryginal, no edited config.
On dedicated server, there is no mystical gemstone icon and Cortidd#5254 on OdinPlus Discord say that there is these same problem with trader.
On singleplayer everything works properly.
![image (1)](https://user-images.githubusercontent.com/25538442/207045108-56608172-b373-47be-afe8-f8bc42960bcf.png)
![image (2)](https://user-images.githubusercontent.com/25538442/207045116-206f1e1f-2f99-473a-b0d4-2a361b957a27.png)
![image (3)](https://user-images.githubusercontent.com/25538442/207045122-18820337-9524-440c-bf7e-edb20627fde3.png)

**Comment by Lime18** [comment]
I have the same problem

**Comment by blaxxun-boop** [comment]
This has been addressed in v1.3.9

**Comment by tgstyle** [comment]
I am having the same issue in 1.4.3. No Mystical gemstone spawns at all on my dedicated server. Is there a way to spawn it manually?

**Comment by blaxxun-boop** [comment]
No, you are not having the same issue. The issue was that the icon of the trader on the map disappeared after logging out and back in. This has been fixed a long time ago.

If you added the mod to an existing world, you will have to spawn in the trader yourself, e.g. with `locations_add jc_gacha_location` from upgrade world. If the mod was installed during world generation, you will have the trader on your map and just need to find it.

**Comment by tgstyle** [comment]
The mod was added before the world generation happened. We have explored every meadows and the trader does not exist. I will spawn it in manually, thanks for the info.
