### ISSUE TITLE
Auga Support

### ISSUE THREAD

**Issue by SaltSouls** [blaxxun-boop/Jewelcrafting#24]
I would love it if this mod added support for Auga. Both mods are great, and it would be nice if I could play with both enabled without getting console error spam every time I opened my inventory.

**Comment by blaxxun-boop** [comment]
Not gonna happen, sorry.
You have to recode your entire mod, to make it somewhat compatible with AUGA and even then it barely works.
AUGA doesn't have many users, so it's really not worth the struggle.

Suggestion: Use Minimal UI instead of AUGA. It works with other mods that touch the UI out of the box and can be made to look exactly like AUGA.
