### ISSUE TITLE
Most Recent Update will not load

### ISSUE THREAD

**Issue by LorneEO** [blaxxun-boop/Jewelcrafting#27]
After the update about half and hour ago, Jewlcrafting will not load. Here is the log error I received:

[Error  :   BepInEx] Could not load [Jewelcrafting 1.3.9] because it is incompatible with: org.bepinex.plugins.valheim_plus

**Comment by blaxxun-boop** [comment]
Yup, remove Valheim Plus, if you wanna use Jewelcrafting.
The amount of issues that Valheim Plus causes is ridiculous and I am sick and tired of it.

**Comment by healiha** [comment]
Hey @blaxxun-boop,

I'm one of the devs still working on Valheim Plus.
I wouldn't mind getting in touch so we can make the required changes on our side for both our mods to be compatible.

We've always been open to any discussion in that sense, feel free to contact me through discord if this is something you want to take a look at.

**Comment by blaxxun-boop** [comment]
@healiha

so far I have:
- Valheim Plus makes the config application fail, causing all gems to have no effect.
- Valheim Plus breaks the custom tooltips of socketed items, displaying the default tooltip instead.
- Valheim Plus breaks the custom background of socketed items, if you use the extra equipment inventory rows, which prevents you from opening chests, for whatever reason.

This does not affect everyone, so it's probably some config settings in Valheim Plus, which cause these issues for people.

**Comment by healiha** [comment]
Thanks for the report @blaxxun-boop

I'll take a look at this next week when I'm off from work and get back to you ASAP.

**Comment by Malus565** [comment]
Been watching to see if there was any further comments on this.  Excited that @healiha from Valheim Plus team is willing to work with @blaxxun-boop .  I hoping you guys are able to fix the compatibility issue soon so that both Valheim Plus and Jewelcrafting are compatible again.  Love both mods for sure.

**Comment by Malus565** [comment]
@blaxxun-boop @healiha Were you guys able to work out the issues and is Jewelcraft compatible again with Valheim Plus??

**Comment by healiha** [comment]
Hello @Malus565 - I haven't had time to work on anything related ot Valheim due to wrk but this is as the top of my to-do list.
Some part of V+ have been poorly designed and this is why quite a few mods are not compatible with it. I have no idea as to how long it would take to rework all of this but I'll try to do my best to do one of those at a time.

@blaxxun-boop I found out where those issues are coming from and I'll need to rewrite some really old code to make things right. I guess most of the issues encountered with other mods are also due to wrong choices that were made at some point in time(ie. returning false in a prefix function - no idea why this is even here).

As soon as I have some time to work on any of this, I'll post an update here.

**Comment by Malus565** [comment]
@healiha Awesome, thank you very much :)
