### ISSUE TITLE
Incompatible with ValheimPlus .9.9.11

### ISSUE THREAD

**Issue by shall-zdata** [blaxxun-boop/Jewelcrafting#35]
Seems to be incompatible I have the same issue with the dualwield. Is this something new with mistlands or are they just incompatible.

**Comment by blaxxun-boop** [comment]
- Valheim Plus makes the config application fail, causing all gems to have no effect.
- Valheim Plus breaks the custom tooltips of socketed items, displaying the default tooltip instead.
- Valheim Plus breaks the custom background of socketed items, if you use the extra equipment inventory rows, which prevents you from opening chests, for whatever reason.

The devs of Valheim Plus have said multiple times that they want to be the only mod that people use and that they do not care about breaking other mods. I'd strongly recommend to remove Valheim Plus as soon as possible, since the modding community is sick and tired of having to work around all the bullshit that Valheim Plus does and quite a few people are in the process of making all their mods incompatible with Valheim Plus. It's just a terrible mod.

**Comment by shall-zdata** [comment]
Thanks for the information. I'm new to modding so I hadn't read that
anywhere yet ;) I look forward to trying out your mods and work.

Thanks!
