### ISSUE TITLE
Graphic Issue with Extended Player Inventory (aedenthorn)

### ISSUE THREAD

**Issue by Sythalin** [blaxxun-boop/Jewelcrafting#60]
Trying this mod out for the first time, ran into a small graphic issue with [Extended Player Inventory](https://www.nexusmods.com/valheim/mods/1356) by aedenthorn.  When placing arrows into the quick keys, the HUD copies do not display/update the currently active arrows.

EPI (by itself):
![Extended Inventory](https://github.com/blaxxun-boop/Jewelcrafting/assets/4165258/da1abe95-7cb3-4a6f-99ed-0dd28f819d3c)

EPI + Jewelcrafting:
![JC + EI](https://github.com/blaxxun-boop/Jewelcrafting/assets/4165258/2de85de9-dbdb-4c56-80b4-d5f6c3a183b9)

Any chance of getting a fix for this?

**Comment by blaxxun-boop** [comment]
Not an issue with Jewelcrafting, but with your inventory mod. So, would have to get fixed by aedenthorn.

Otherwise, you can always switch to https://valheim.thunderstore.io/package/Azumatt/AzuExtendedPlayerInventory/ which does the same thing, but doesn't have this issue. Just make sure to dump all your stuff into a chest, before you switch the mod. And make sure to enable the features you want in the config, since they aren't enabled by default.
