### ISSUE TITLE
Incompatibility with RandyKnapp's Auga

### ISSUE THREAD

**Issue by BranTuna** [blaxxun-boop/Jewelcrafting#8]
Hello, I just wanted to report the incompatibility with Auga. which is the only thing preventing us from making the switch to Jewelcrafting. I can't drop Auga because it helps my mother see the UI elements better. The log keeps complaining about a transform with the recipes due to jewelcrafting, making nothing show up in the crafting tab, which is the only real problem that I've noticed. If this is something that cannot or will not be fixed, please let us know. Thanks,

- BranTuna

**Comment by BranTuna** [comment]
`[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.GetComponent[T] () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
Jewelcrafting.GemStones+AddSocketAddingTab.TabOpen () (at <6cb61fe569f647e8b47e951d54dac523>:0)
(wrapper dynamic-method) Jewelcrafting.GemStones+ChangeDisplay.DMD<Jewelcrafting.GemStones+ChangeDisplay::Postfix>(InventoryGui)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::UpdateRecipe>(InventoryGui,Player,single)
(wrapper dynamic-method) InventoryGui.DMD<InventoryGui::Update>(InventoryGui)`

**Comment by blaxxun-boop** [comment]
Hey,

I won't be adding support for Auga. It's a lot of work and pretty much requires you to have two separate copies of the same mod, with different code for the UI and Auga is hardly used by anyone, because of its incompability with everything that touches the UI.

Just look at the Epic Loot commit that Randy made to add support for Auga back then. Rewrote half the mod and it still doesn't work perfectly and has some weird glitches with Auga.

Sorry about any inconveniences that this might cause for you.

Cheers.

**Comment by BranTuna** [comment]
Thanks for letting me know. I had a hard time just getting the majority of the mods I had to work with it via configurations, so I get the gist. Thinking of doing the switch anyway and buying mum a new pair of glasses, lol. Fantastic mod, btw!

**Comment by BranTuna** [comment]
Was looking through the code here and there for Auga's API, and Its completely up to you but I was wondering if I could fork this and _TRY_... It would be my first modding adventure, but Ive got the time for it. I'd obviously need some help, so I was thinking I could hop into discord and give it a shot, if that's alright with you...

**Comment by blaxxun-boop** [comment]
Well, you are obviously free to try that, yes.
