### ISSUE TITLE
translation problem

### ISSUE THREAD

**Issue by Timeunderthemoonlight** [blaxxun-boop/Jewelcrafting#9]
![QQ截图20220824104302](https://user-images.githubusercontent.com/111029441/186307870-8a6cfca6-5dfa-4401-ac30-dbe1d5adb2db.png)
Hello, you have left 2 untranslated content

**Comment by blaxxun-boop** [comment]
Those are from Soulcatcher, not Jewelcrafting.
That being said, there will always be some texts which aren't translated, because I am not doing the translations myself and whenever I add new texts to the mod, which happens with almost every single update, someone will have to translate the texts first.
